<?php
/**
 * nessus-report-parser -- cvss.phtml
 * User: Simon Beattie
 * Date: 11/06/2014
 * Time: 12:23
 */


$rowCount = 0;

$cell_template = '';

$filename = 'Nessus';

if ('html' == $reportFormat) {

    $row_start = "  <tr>\n";
    $row_end = "  </tr>\n";
    $cell_start = "    <td>";
    $cell_end = "</td>\n";
    $cell_sep = '';
    $ip_protector = '';
    $sep_multiline = '<br />';

    include(__DIR__ . '/../includes/nessusReportHeaderCSV.phtml');

    echo "\n<h1>$reportHeader</h1>";
    echo "\n<table border=0 cellpadding=0 cellspacing=0>\n\n";

} else {

    $row_start = '';
    $row_end = "\r\n";
    $cell_start = '';
    $cell_end = '';
    $cell_sep = "\t";
    $ip_protector = " ";  // Excel trashes IPs by trying to convert 'em into something false recoznized; add " " sing in front for Excel to regard this as strings
    $sep_multiline = ', ';

    $app->response->headers->set('Content-Type', 'text/csv');

    $app->response->headers->set('Content-Disposition', 'attachment; filename="'. $filename . '.csv"');

    $app->response->headers->set('Cache-Control', 'must-revalidate');

    $app->response->headers->set('Pragma', 'must-revalidate');

    echo chr(0xef). chr(0xbb). chr(0xbf);

    echo $reportHeader. $row_end. $row_end;
}

print($row_start .
        $cell_start. NLS::get('severity'). $cell_end. $cell_sep.
        $cell_start. NLS::get('vuln_categories_title_main') . $cell_end. $cell_sep.
        $cell_start. NLS::get('vuln_categories_subtitle_main') . $cell_end. $cell_sep.
        $cell_start. NLS::get('vuln_categories_solution_main') . $cell_end. $cell_sep.
        $cell_start. NLS::get('host_ip') . $cell_end. $cell_sep.
      $row_end
    );



foreach ($reportData as $hostData) {

    global $import;

    for ($n = 0; $n < count($hostData['hosts']); $n++) {

        $hostData['hosts'][$n] = $import->ipUnpad($hostData['hosts'][$n]);
    }

    $hosts = join($sep_multiline, $hostData['hosts']);

    $rowCount++;

        print($row_start .
                $cell_start. NLS::get($hostData['severity']) . $cell_end. $cell_sep.
                $cell_start. $hostData['categories_title_main'] . $cell_end. $cell_sep.
                $cell_start. $hostData['categories_subtitle_main'] . $cell_end. $cell_sep.
                $cell_start. $hostData['categories_solution_main'] . $cell_end. $cell_sep.
                $cell_start. $ip_protector. $hosts. $cell_end. $cell_sep.
              $row_end
            );
}

if ('html' == $reportFormat) {

    echo "</table>";

    include(__DIR__ . '/../includes/footer.phtml');
}


