<?php
/**
 * nessus-report-parser -- footer.phtml
 * User: Simon Beattie
 * Date: 12/06/2014
 * Time: 14:43
 */

echo '
        <p />
        <div id="footer">
            Nessus Bulk Parser © ' . date("Y") . ' <a href="http://sva.de">SVA GmbH</a> :: <a href="https://twitter.com/sglusnevs">Sergejs Glusnevs</a><br />
            Based on Nessus Reports Parser by <a href="https://www.randomstorm.com">RandomStorm</a><br />
            Originally Designed by <a href="https://twitter.com/si_bt">Simon Beattie</a> <br />
            Licensed under GNU/GPL
        </div>
    </body>
</html>
';
