<?php
/**
 * nessus-report-parser -- index.phtml
 * User: Simon Beattie
 * Date: 12/06/2014
 * Time: 16:09
 */

include(__DIR__ . '/../includes/menuHeader.phtml');

echo '
<p class="header" >I was very impressed by Nessus Report Parser by Simon Beattie,<br />but we had special requirements to be able to parse reports for large environments, here occured this fork</p>
<div id="updateListBox">
    <div id="updateList">
        <ul>
            <li>Reports added to rank hosts after CVSS values</li>
            <li>Reports and MySQL tables added to be able to classify hosts after custom vulnerability groups
            <li>CSV exports added for the new reports</li>
            <li>MySQL schema optimized (indexes added)</li>
            <li>Basic internationalization support (see Library/Translations.php)</li>
            <li><font color="red">Please note:</font> you need the following changes to your reporting system to accomodate large reports:
            <ul>
                <li>Host or VM better have huge amount of RAM (like 4GB), otherwise Python file merger dies without further explanations</li>
                <li>Set the following in your php.ini: `upload_max_filesize = 2048M´, `post_max_size = 2048M´ to be able to upload huge reports</li>
            </ul>
            </li>
        </ul>
    </div>
</div>
';

echo'
<div id="updateListBox">
    <div id="updateList">
        <ul>
            <li>21st April 2016:</li>
            <ul>
                <li>Initial changes</li>
            </ul>
        </ul>
    </div>
</div>
<hr />
';

include(__DIR__ . '/../includes/footer.phtml');
